- name: Install and start MongoD
  hosts: all
  become: true
  tasks:
    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927
    - name: Add specified repository into sources list.
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present
        filename: mongodb-org-3.2
    - name: Update repositories cache and install "mongodb-org" package
      apt:
        name: mongodb-org
        update_cache: yes
    - name: Make sure a service is running and enable it
      systemd:
        state: started
        name: mongod
        enabled: yes
        